image: harbor.javalabs.com.cn/javalabs-tools/ci-base:0.0.2

stages:
   - build
   - release

build:
   stage: build
   script:
   - mvn clean package
   
release:
   stage: release
   script:
   - mvn dockerfile:build dockerfile:push
   only:
    - master
    - /^release-.*$/
    - /^hotfix-.*$/
    
before_script:
   - mkdir -p /root/.docker
   - echo "{\"auths\":{\"harbor.javalabs.com.cn\":{\"auth\":\"$(echo -n admin:Harbor12345 | base64)\"}}}" > /root/.docker/config.json