image: pdsd-registry.infinitus.com.cn/tools/cibase:0.9.1

stages:
   - build
   - release

build:
   stage: build
   script:
   - mvn clean package -U
   only:
    - /^release-.*$/
    - /^hotfix-.*$/
   
release:
   stage: release
   script:
   - mvn clean package deploy dockerfile:build dockerfile:push -Dmaven.test.skip=true -U
   only:
    - master
    - /^release-.*$/
    - /^hotfix-.*$/
    
.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

before_script:
   - *auto_devops
   - mkdir -p /root/.docker
   - echo "{\"auths\":{\"registry.cn-hangzhou.aliyuncs.com\":{\"auth\":\"am9rZXdheTptYWN1bGFAY2xvdWQ=\"}}}" > /root/.docker/config.json