server:
  port: ${SERVER_PORT:8761}
spring:
  application:
    name: ${APPLICATION_NAME:macula-cloud-eureka}
  cloud:
    inetutils:
      ignored-interfaces: ${IGNORED_INTERFACES:eth0}
      preferred-networks: ${PREFERRED_NETWORKS:10.0}
  security:
    user:
      name: ${USER_NAME:macula}
      password: ${PASSWORD:macula2019}
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      VERSION: 1.0.0
  client:
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://macula:macula2019@localhost:8761/eureka}
    registry-fetch-interval-seconds: 10
    disable-delta: true
  server:
    enable-self-preservation: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION:false}
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 3000
    response-cache-auto-expiration-in-seconds: 180
