# Default values for scc-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# pod运行数量
replicaCount: 1

image:
  # 镜像库地址
  repository: registry.cn-hangzhou.aliyuncs.com/macula-cloud/macula-cloud-eureka
  # 镜像版本
  tag: latest
  # 镜像拉取策略
  pullPolicy: Always

initDB:
  # 是禁用始化数据库
  disabled: true

## springboot配置
application:
  server:
     port: 8761
     
metrics:
  # 收集应用的指标数据路径
  path: /actuator/prometheus
  # 性能指标应用分组
  group: spring-boot

logs:
  # 日志收集格式
  parser: spring-boot

resources:
  # k8s中容器能使用资源的资源最大值
  limits:
    # cpu: 100m
    memory: 1.5Gi
  # k8s中容器使用的最小资源需求
  requests:
    # cpu: 100m
    memory: 1Gi